baseURL: "https://patrickpt.github.io/"
title: Pat's Log
paginate: 5
theme: PaperMod

publishDir: docs

canonifyURLs: False

params:
  defaultTheme: auto # dark, light
  disableThemeToggle: false
  # home-info mode
  homeInfoParams:
    Title: "Welcome"
    Content: Hi, i am Patrick. I’m documenting my learning notes, best practices and how-to's on this blog.
  
  # profileMode:
  #       enabled: true
  #       #title: "<Title>" # optional default will be site title
  #       #subtitle: "Hi, i am Patrick. I’m documenting my learning notes, best practices and how-to's on this blog."
  #       imageUrl: "me.jpg" # optional
  #       #imageTitle: "<title of image as alt>" # optional
  #       imageWidth: 180 # custom size
  #       imageHeight: 180 # custom size
  #       buttons:
  #         - name: Posts
  #           url: "/posts"
  #         - name: Tags
  #           url: "/tags"

  ShowShareButtons: True
  ShowReadingTime: true

  assets:
    favicon: "/favicon/favicon.ico"
    favicon16x16:  "/favicon/favicon-16x16.png"
    favicon32x32:  "/favicon/favicon-32x32.png"
    apple_touch_icon:  "/favicon/apple-touch-icon.png"
    #safari_pinned_tab:  "/favicon/safari-pinned-tab.svg"

  socialIcons:
    - name: linkedin
      url: "https://www.linkedin.com/in/patrickschnass/"
    - name: medium
      url: "https://medium.com/@patrickschnass"
    - name: github
      url: "https://github.com/PatrickPT"
  
outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

menu:
  main:
    - identifier: Posts
      name: Posts
      url: /posts/
      weight: 10
    - identifier: Archive
      name: Archive
      url: /archives/
      weight: 30
    - identifier: Search
      name: Search
      url: /search/
      weight: 40
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 50
    - identifier: About
      name: About
      url: /about/
      weight: 20
